In [1]:
import pandas as pd
from dateutil import parser
import numpy as np
data = pd.read_table('./whole_data.csv',sep=',')

In [2]:
data = data[:-811]
# data = data.reset_index()

In [3]:
data

TimeStamp  Value
0      2022-11-16T00:00:00Z  25.93
1      2022-11-16T00:01:00Z  26.80
2      2022-11-16T00:02:00Z  25.87
3      2022-11-16T00:03:00Z  26.15
4      2022-11-16T00:04:00Z  26.50
...                     ...    ...
21595  2022-11-30T23:55:00Z  35.94
21596  2022-11-30T23:56:00Z  35.77
21597  2022-11-30T23:57:00Z  35.28
21598  2022-11-30T23:58:00Z  35.99
21599  2022-11-30T23:59:00Z  36.30

[21600 rows x 2 columns]

In [4]:
value = []
temp = 0
count= 0
for i in range(len(data)):
    count+=1
    temp += data['Value'][i]        
    if(count==1):
        value.append(temp)
        count = 0
        temp=0

In [5]:
value

[25.93,
 26.8,
 25.87,
 26.15,
 26.5,
 26.06,
 26.45,
 25.46,
 25.62,
 26.37,
 25.6,
 26.53,
 25.62,
 26.52,
 26.99,
 26.0,
 26.91,
 26.49,
 26.11,
 26.93,
 26.21,
 26.725,
 25.78,
 26.96,
 25.68,
 26.67,
 26.52,
 26.01,
 26.55,
 26.08,
 26.7,
 26.85,
 25.54,
 26.74,
 25.91,
 25.44,
 26.49,
 37.61,
 37.74,
 46.95,
 47.91,
 47.01,
 47.21,
 47.97,
 47.88,
 47.81,
 47.2,
 46.86,
 46.99,
 47.72,
 47.59,
 46.63,
 47.03,
 46.79,
 46.44,
 47.05,
 47.29,
 47.77,
 46.36,
 46.71,
 46.66,
 47.5,
 47.55,
 46.49,
 47.01,
 47.45,
 46.78,
 47.0,
 47.39,
 47.89,
 46.09,
 46.85,
 47.17,
 46.93,
 47.17,
 47.26,
 46.79,
 46.99,
 47.47,
 48.17,
 46.75,
 47.26,
 48.02,
 47.26,
 47.44,
 47.13,
 48.05,
 47.46,
 47.31,
 46.6,
 47.9,
 47.13,
 46.66,
 47.27,
 46.55,
 46.98,
 46.99,
 46.41,
 46.95,
 46.58,
 46.55,
 46.96,
 46.88,
 47.66,
 14.06,
 25.59,
 24.94,
 25.43,
 25.66,
 24.96,
 25.02,
 25.37,
 24.53,
 24.62,
 25.38,
 25.06,
 25.15,
 25.61,
 25.21,
 24.9,
 25.44,
 25.23,
 24.31,
 25.46,
 24.6,
 24.89,
 26

In [6]:
hour_data = []
temp = 0
count= 0
for i in range(len(value)):
    count+=1
    temp += data['Value'][i]
    if(count==60):
        hour_data.append(temp)
        count = 0
        temp=0

In [7]:
hour_data

[2038.285,
 2464.8500000000004,
 1518.2150000000001,
 1524.8500000000004,
 1524.8950000000004,
 1523.9050000000004,
 1539.3899999999999,
 1562.9249999999995,
 1579.0149999999999,
 1594.9700000000005,
 1574.0100000000002,
 1564.0,
 2779.925,
 2847.435,
 2841.7699999999995,
 2558.2599999999998,
 2254.56,
 2556.9149999999995,
 2649.8150000000005,
 2724.7949999999996,
 2461.6149999999993,
 2387.2100000000005,
 2390.61,
 2768.7250000000004,
 2260.9299999999994,
 1534.2599999999993,
 1529.1199999999997,
 1538.56,
 1534.9800000000005,
 1534.7000000000003,
 1534.9600000000003,
 1564.165,
 1565.3799999999999,
 1561.8149999999998,
 1572.195,
 1569.3050000000005,
 1563.9800000000005,
 1577.3900000000003,
 1607.6999999999998,
 1565.23,
 1531.1349999999998,
 1542.6449999999995,
 1959.07,
 2173.01,
 2165.7299999999996,
 2180.89,
 2175.4549999999995,
 2385.110000000001,
 2789.04,
 2549.295,
 1906.9699999999998,
 1533.29,
 1525.995,
 1525.0999999999995,
 1525.2100000000005,
 1551.9050000000004,
 1549.

In [8]:
hour = []
ct = 0
for i in range(len(hour_data)):
    hour.append(ct)
    ct += 1
    if(ct==24):
        ct = 0

In [9]:
hour[0]

0

In [10]:
day = []
ct = 0
for i in range(len(hour_data)):
    day.append(data['TimeStamp'][i*60][8:10])

In [12]:
day

['16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '16',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '17',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '18',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '19',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '20',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',
 '21',

In [13]:
x = np.empty([len(hour_data)-24, 26], dtype = float)
y = np.empty([len(hour_data)-24, 1], dtype = float)

In [19]:
x

array([[1.600000e+01, 0.000000e+00, 2.038285e+03, ..., 2.387210e+03,
        2.390610e+03, 2.768725e+03],
       [1.600000e+01, 1.000000e+00, 2.464850e+03, ..., 2.390610e+03,
        2.768725e+03, 2.260930e+03],
       [1.600000e+01, 2.000000e+00, 1.518215e+03, ..., 2.768725e+03,
        2.260930e+03, 1.534260e+03],
       ...,
       [2.800000e+01, 2.100000e+01, 2.758560e+03, ..., 2.179055e+03,
        2.413785e+03, 2.768950e+03],
       [2.800000e+01, 2.200000e+01, 2.588260e+03, ..., 2.413785e+03,
        2.768950e+03, 2.772860e+03],
       [2.800000e+01, 2.300000e+01, 2.154665e+03, ..., 2.768950e+03,
        2.772860e+03, 2.773185e+03]])

In [9]:
# import numpy as np
# from sklearn.linear_model import LinearRegression
# lr = LinearRegression()
# lr.fit(train_X, train_y)
# lr.score(train_X,train_y)
# print(lr.score(train_X,train_y))

In [18]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from joblib import dump, load
for k in range(24,25):
    x = np.empty([len(hour_data)-24-k, 26])
    y = np.empty([len(hour_data)-24-k, 1])
    for i in range(x.shape[0]):
        x[i][0] = day[i]
        x[i][1] = hour[i]
        x[i][2:] = hour_data[i:i+24]
        y[i] = hour_data[i+k]
    lr = LinearRegression()
    lr.fit(x, y)
    lr.score(x,y)
    print(k,"= ",lr.score(x,y))
#dump(lr, 'lrmodel.joblib')

24 =  0.7969307127998051


['lrmodel.joblib']

In [21]:
lr.predict(x)

array([[2567.86049188],
       [1955.15096488],
       [1418.152652  ],
       [1708.21900667],
       [1432.96750823],
       [1583.31420418],
       [1517.21036416],
       [1606.94280759],
       [1675.3668295 ],
       [1525.08501371],
       [1514.25814588],
       [1538.16037873],
       [1676.60001511],
       [1706.33028763],
       [1706.66704763],
       [1538.27933615],
       [1561.96352039],
       [1682.32314279],
       [1685.46086518],
       [1995.44293974],
       [2098.0303389 ],
       [2161.94117496],
       [2187.70715151],
       [2140.8803519 ],
       [2340.65079512],
       [2681.21499953],
       [2303.42981346],
       [1778.99946952],
       [1480.94790347],
       [1563.67497705],
       [1579.38333895],
       [1564.01085956],
       [1583.02460997],
       [1625.1309035 ],
       [1577.23751546],
       [1557.98040783],
       [1588.70087138],
       [1732.99057341],
       [2322.33085532],
       [2314.0287745 ],
       [2695.75136584],
       [2134.704

In [17]:
y

array([[2260.93      ],
       [1534.26      ],
       [1529.12      ],
       [1538.56      ],
       [1534.98      ],
       [1534.7       ],
       [1534.96      ],
       [1564.165     ],
       [1565.38      ],
       [1561.815     ],
       [1572.195     ],
       [1569.305     ],
       [1563.98      ],
       [1577.39      ],
       [1607.7       ],
       [1565.23      ],
       [1531.135     ],
       [1542.645     ],
       [1959.07      ],
       [2173.01      ],
       [2165.73      ],
       [2180.89      ],
       [2175.455     ],
       [2385.11      ],
       [2789.04      ],
       [2549.295     ],
       [1906.97      ],
       [1533.29      ],
       [1525.995     ],
       [1525.1       ],
       [1525.21      ],
       [1551.905     ],
       [1549.54      ],
       [1561.885     ],
       [1571.61      ],
       [1566.65      ],
       [1615.425     ],
       [2158.6       ],
       [2335.445     ],
       [2768.775     ],
       [2445.13      ],
       [2268.05 

In [22]:
X = list(lr.predict(x))

In [23]:
for i in range(len(X)):
    if int(lr.predict(x)[i] - y[i]) >200:
        print(lr.predict(x)[i])
        print(y[i])
        print(lr.predict(x)[i] - y[i])

[2567.86049188]
[2260.93]
[306.93049188]
[1955.15096488]
[1534.26]
[420.89096488]
[2303.42981346]
[1906.97]
[396.45981346]
[1778.99946952]
[1533.29]
[245.70946952]
[2695.75136584]
[2445.13]
[250.62136584]
[2381.88660392]
[2177.135]
[204.75160392]
[1984.05854729]
[1671.675]
[312.38354729]
[2739.97691186]
[2525.84]
[214.13691186]
[2014.60875825]
[1513.075]
[501.53375825]
[2221.14154225]
[2009.71]
[211.43154225]
[2254.87675612]
[1986.49]
[268.38675612]
[2450.06840389]
[1999.85]
[450.21840389]
[2596.21963322]
[2136.91]
[459.30963322]
[2440.328765]
[2154.665]
[285.663765]


In [24]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

def PolynomialRegression(degree=2, **kwargs):
    return make_pipeline(PolynomialFeatures(degree),
                         LinearRegression(**kwargs))
plr=PolynomialRegression(degree=3)
plr.fit(x,y)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures(degree=3)),
                ('linearregression', LinearRegression())])

In [25]:
plr.score(x,y)

1.0

In [26]:
lr.score(x,y)

0.7969307127998051

In [27]:
(lr.predict(x))[180] #???

array([2069.69375388])

In [28]:
y[180]

array([2000.22])